### ISSUE TITLE
use budget

### ISSUE THREAD

**Issue by gwenhael-le-moine** [davidkeegan/dklrt#2]
Would it be possible to use ledger budgeting [ http://www.ledger-cli.org/3.0/doc/ledger3.html#Budgeting ] as the source ?

**Comment by davidkeegan** [comment]
Hi,

No. When I wrote the package I looked at automated and
periodic transactions, and they didn't seem to do what I
wanted.

Regards,
David.

gwenhael writes:

> ## Would it be possible to use ledger budgeting [ http://www.ledger-cli.org/3.0/doc/ledger3.html#Budgeting ] as the source ?
> 
> [David Keegan dksw@eircom.net 01 2988743 or 086 8777046]
> [56 Roebuck Downs Dublin 14 IRELAND]
